### ISSUE TITLE
Action Text links within Turbo Streams use the wrong host

### ISSUE THREAD

**Issue by brian-kephart** [hotwired/turbo-rails#155]
This is a duplicate of #54, which was closed by the person who opened it. I also opened [an issue](https://github.com/rails/rails/issues/41795) on the Rails repo, because I think this might be an issue with things besides Turbo. I decided to open it here as well though since it's directly related to my use of Turbo.

When rendering an Action Text attachment with a Turbo Stream using a background job via the `broadcasts_to` [method](https://github.com/hotwired/turbo-rails/blob/fec33d9bc767aec612b283620d2a74e78c1f90ae/app/models/concerns/turbo/broadcastable.rb#L54), the host in the attachment is 'example.org' instead of 'localhost' or whatever else it should be. Repro here: https://github.com/brian-kephart/rendering_bug.git

**Comment by dhh** [comment]
You have to configure the application renderer default value when rendering outside the request/response context. There's a default initializer for this in config/initializers/application_controller_renderer.rb. Feel free to open a PR to document this somewhere.

**Comment by brian-kephart** [comment]
Thank you for responding. I have already tried using that initializer before filing this issue, so either I'm doing it wrong or the code in the initializer is not working as intended. For example, the following initializer code has no effect on this issue in the repro app:

```ruby
# config/initializers/application_controller_renderer.rb

ActiveSupport::Reloader.to_prepare do
  ApplicationController.renderer.defaults.merge!(
    http_host: 'localhost'
  )
end
```

If that code is supposed to solve this issue, then there is a bug. If that is the wrong code, then I think the [generator](https://github.com/rails/rails/blob/291a3d2ef29a3842d1156ada7526f4ee60dd2b59/railties/lib/rails/generators/rails/app/templates/config/initializers/application_controller_renderer.rb.tt) for that initializer needs to be changed to give clearer guidance. I'd be willing to document the feature once the correct setup is established.

**Comment by dhh** [comment]
Looks like Action Text is using a default_renderer derived from ActionController::Base instead of ApplicationController. So you might have to set config.action_text.default_renderer to ApplicationController.renderer in an initializer. Seems like that should be the default, though, so it's easier. Don't recall why that's not so.

**Comment by brian-kephart** [comment]
It looks like that used to be the default, but it was changed in https://github.com/rails/rails/commit/614e813161ad8f6e13ad19aedd577acdd976d9d6 to address a variety of issues.

**Comment by brian-kephart** [comment]
`config.action_text` returns a `NoMethodError` unless I'm running on edge (I've been using 6.1.3.1)

On edge, `config.action_text.default_renderer = ApplicationController.renderer` does not affect this issue.

The only thing I've found so far to get it working is:
```ruby
# config/application.rb (or an initializer)

config.action_controller.default_url_options = { host: 'localhost', port: 3000 }
```

Changing the global default seems a bit heavy-handed, and I'm not sure how to adjust it for apps that serve multiple domains. I guess that's true of the `application_controller_renderer.rb` solution as well, though.

**Comment by dhh** [comment]
```ruby
    initializer "action_text.renderer" do
      ActiveSupport.on_load(:action_text_content) do
        self.default_renderer = Class.new(ActionController::Base).renderer
      end
```

Yeah, looks like you'll have to set it manually with `ActionText::Base.default_renderer` or something like that. Do look into the reasons why that is and feel free to open a PR with improvements.

**Comment by brian-kephart** [comment]
I'm out of my depth here, but gradually finding my way around. In checking assumptions, I found that rendering through the `broadcasts_to` method uses the default renderer, which is entirely expected. However, it doesn't use the specified defaults. Changing them does not produce results. See below:
```ruby
# config/initializers/action_controller_renderer.rb

ActiveSupport::Reloader.to_prepare do
  # This does not work
  ActionText::Content.default_renderer.defaults.merge!(
    http_host: 'localhost',
    port: 3000
  )

  # This works
  ActionText::Content.default_renderer.instance_variable_get(:@env).merge!(
    'HTTP_HOST' => 'localhost:3000'
  )
end
```

I've updated the repro app to add some info about the renderer into the views for visibility into what's going on.

**Comment by brian-kephart** [comment]
After looking at this for quite some time, I'm reasonably sure it's not a Turbo issue at all. The issue seems to be within Action Text. It seems that Action Text...

- ignores the renderer defaults in favor of the request environment (there's even [a test](https://github.com/rails/rails/blob/57cbf4136fa0e7cab69286706bd2a0d967344e6d/actiontext/test/integration/controller_render_test.rb#L6) for this), which doesn't have as convenient of an accessor method for setting a default.
- is inconsistent in how it renders attachment URLs (the url attribute of `<action-text-attachment>` is correct, but the src attribute of the `<img>` is incorrect).

Since this is still relevant to turbo-rails users, I can document the `default_url_options` approach above, but https://github.com/rails/rails/issues/39566 might make it obsolete. Should I go ahead anyway?

**Comment by dhh** [comment]
Seems like we should still fix it if Action Text isn't using the default render options. That smells like a bug to me.

When the request renderer is available, that should be used. The default renderer is the fallback when you're rendering outside of the request cycle.

**Comment by dhh** [comment]
Either way, need to address this in Rails. Not turbo-rails.

**Comment by seanharmer** [comment]
For those hitting a similar issue with Active Storage urls being rendered incorrectly outside of a controller, e.g. with a broadcast_replace_to, see https://github.com/rails/rails/issues/41795.

Workaround for that case is to wrap in url_for().

**Comment by tenpaiyomi** [comment]
@dhh Going to bump this up as I actually came across this issue both in `turbo-rails` and `view_components`.

I isolated down the issue to the [`ActionController::Renderer#render`](https://github.com/rails/rails/blob/5fa7049856cab9fbd188cad90d57947252ef9ea8/actionpack/lib/action_controller/renderer.rb#L91) method, specifically when the [following line](https://github.com/rails/rails/blob/5fa7049856cab9fbd188cad90d57947252ef9ea8/actionpack/lib/action_controller/renderer.rb#L94) is called:

`request = ActionDispatch::Request.new @env`

As best I can tell with following the logic, the default `ApplicationController.renderer` is created with the defaults and runs through the [normalize_keys](https://github.com/rails/rails/blob/5fa7049856cab9fbd188cad90d57947252ef9ea8/actionpack/lib/action_controller/renderer.rb#L105) method, setting all the default values for the initial `@env`.  

From there, from what I've worked out through my general digging, it seems like regardless of changing the defaults on the `ApplicationController.renderer` via the `ApplicationController.renderer.defaults.merge!` initializer, it will never actually affect the `render` method unless a new instance of `ApplicationController.renderer` is created without passing an `env` value such that it creates a new `env` with the updated `defaults`

I was able to work around the problem by using a variant of the solution presented by @brian-kephart, only instead of attempting to change the `@env` instance variable on the `ActionText::Content.default_renderer`, I changed the `@env` instance variable on the `ApplicationController.renderer`.  This resulted in getting proper schema and hosts when using `render` in both `turbo-rails` broadcast calls and `view_components`.

```
ApplicationController.renderer.instance_variable_get(:@env).merge!(
    'HTTP_HOST' => 'randomhost.com'
    'HTTPS' => (Rails.env.staging? || Rails.env.production?) ? "on" : "off"
  )
```

It feels like any calls to update the renderer `defaults` should go through a similar process in `normalize_keys` again, only omitting the [check for an existing key](https://github.com/rails/rails/blob/5fa7049856cab9fbd188cad90d57947252ef9ea8/actionpack/lib/action_controller/renderer.rb#L111) via the `unless new_env.key?(key)`.  Potentially something similar to the [`with_defaults(defaults)`](https://github.com/rails/rails/blob/5fa7049856cab9fbd188cad90d57947252ef9ea8/actionpack/lib/action_controller/renderer.rb#L58) method except geared towards updating the instance of the `ActionController::Renderer` it's being called against:

```
def update_defaults(new_defaults)
  defaults.merge!(new_defaults)
  @env = normalize_keys defaults, @env, true
end

...

def normalize_keys(defaults, env, refresh = false)
  new_env = {}
  env.each_pair { |k, v| new_env[rack_key_for(k)] = rack_value_for(k, v) }

  defaults.each_pair do |k, v|
    key = rack_key_for(k)
    new_env[key] = rack_value_for(k, v) if !new_env.key?(key) || refresh
  end

  new_env["rack.url_scheme"] = new_env["HTTPS"] == "on" ? "https" : "http"
  new_env
end
```

Which would then replace the `application_controller_renderer.rb` setup with

```
ActiveSupport::Reloader.to_prepare do
  ApplicationController.renderer.update_defaults(
    http_host: 'example.org',
    https: false
  )
end
```
