### ISSUE TITLE
What is the purpose of Turbo::Broadcastable::broadcasts ?

### ISSUE THREAD

**Issue by fig** [hotwired/turbo-rails#171]
From my reading of the [documentation](https://github.com/hotwired/turbo-rails/blob/2945dcb7c5fc634ad7d459e0872cf04cf8a3576d/app/models/concerns/turbo/broadcastable.rb#L60), the class method `broadcasts` should configure the model to broadcast creates, updates, and destroys to a stream name automatically set to the current model. I would expect the broadcasts to be made to a stream name derived from the model name pluralised, although the pluralisation is not documented explicitly.

In any case, the actual implementation broadcasts to a stream name derived from the `GlobalID` of the model instance. This makes little sense because although a partial can be configured to accept broadcasts from this unique stream name, updates will replace the target element as expected, destroys will leave an  orphaned `turbo-cable-stream-source` tag behind and creating a new model instance has no effect because the broadcast will be made to a channel name that does not exist at the time of rendering.

What are community's thoughts on this?

Apologies if this is the wrong place to ask.

**Comment by danmcge** [comment]
Let's take this to https://discuss.hotwire.dev/.

(Briefly, though, I think what you’re describing is, say, `broadcasts_to :posts`. That’s not what `broadcasts` is for. Imagine you had a `post` that had comments that `broadcasts_to :posts`, but it’s important, for some reason, to broadcast when the title of the post changes. That’s when you’d reach for `broadcasts`. The `<%= turbo_stream_for @post %>` call in your template would pick up both the comments and the change to the post itself. And it would only be the changes to, and the comments for, that specific post, because the stream is scoped by the ID.)
