### ISSUE TITLE
Turbo and Rails back URL option

### ISSUE THREAD

**Issue by savroff** [hotwired/turbo-rails#211]
Hey team,
First of all, thank you for the amazing library! ❤️  

So we are trying to use Turbo a lot more in our app, and we figured that currently, you are losing an option to use standard Rails functionality of going `:back` as it follows back to:

```ruby
def _back_url # :nodoc:
  _filtered_referrer || "javascript:history.back()"
end

def _filtered_referrer # :nodoc:
  if controller.respond_to?(:request)
    referrer = controller.request.env["HTTP_REFERER"]
    if referrer && URI(referrer).scheme != "javascript"
      referrer
    end
  end
rescue URI::InvalidURIError
end
```

And whenever it's getting to `"HTTP_REFERER"`  - it will equal to current page and will not go back. 
But `javascript:history.back()`will work.

Can we figure out how to fix it?
Thank you!

**Comment by mikecheverda** [comment]
I got the same issue in my app a few days ago, after doing "yarn upgrade", which updated a bunch of packages.

I'm sure turbo-rails library works well because I checked it on my other application, which had beta.8 installed and after the same "yarn upgrade", HTTP_REFERRER was always set to the same location.

Most of the updates in yarn.lock were related to @babel/* 

Haven't got time to pinpoint exactly what cause it.

**Comment by antonioJASR** [comment]
I have the same issue. I'm using `"@hotwire/turbo-rails": "^7.0.0-rc.1"` in my package.json.

**Comment by frederfred** [comment]
I believe this is the relevant issue in the [`hotwired/turbo`](https://github.com/hotwired/turbo) repo: https://github.com/hotwired/turbo/issues/332

**Comment by kirillplatonov** [comment]
It's fixed in turbo and will be shipped in rc2: https://github.com/hotwired/turbo/pull/345
