### ISSUE TITLE
Response fails to render (client-side) if view files don't contain `.html` in the name

### ISSUE THREAD

**Issue by cmartyn** [hotwired/turbo-rails#22]
We have a relatively large Rails codebase that uses the slim templating language along with Turbolinks (including native Turbolinks wrappers for iOS and Android). In general, it has worked great for us for years! (Thanks!)

But when I upgraded to Turbo, all our links appeared to stop working: The URL would change, and the client would make the request to the server (per browser console), and the server would render a response (per the Rails logs), but the DOM would never be updated with the content rendered by the server.

After a lot of trial and error, I finally figured out why: Our view files are generally named `file_name.slim` rather than `file_name.html.slim`. There was one link I could find that *did* work, and it happened to be one of the few files that included the `.html` extension in its name.

Using this naming convention for our view files hasn't caused us issues before, so it's technically a regression from Turbolinks 5. I'm not sure if this is a common pattern that could affect lots of people, or if we're the only app doing it and we've been doing it wrong for years.

I figured it was worth posting here to both clarify our upgrade path (should we bite the bullet and do a massive file rename, or will this be treated as a bug to be fixed?) and to save others time if they encounter the same issue.

**Comment by dhh** [comment]
That's a good catch. It's caused by the need to switch rendering formats when streams are rendered, see https://github.com/hotwired/turbo-rails/blob/6ba6e005990682a61d82067dc141afdc98bd6c22/app/channels/turbo/streams/broadcasts.rb#L26. Can only force that switch if the mime type is present in the template.

Not sure the best way to catch/alert about this. Maybe there's a way to catch the exception in https://github.com/hotwired/turbo-rails/blob/6ba6e005990682a61d82067dc141afdc98bd6c22/app/channels/turbo/streams/broadcasts.rb#L63-L65 and rethrow with better error messaging? Please do investigate!

**Comment by dvisockas** [comment]
@cmartyn, after a weekend of digging found a rather hacky fix: remove 'turbo-stream;' from `Content-Type` headers: 
```ruby
if response.headers['Content-Type'].include? 'text/html'
  response.headers['Content-Type'].remove!('turbo-stream;')
end
```
