### ISSUE TITLE
Success with updating part of a form using turbo streams

### ISSUE THREAD

**Issue by jonsgreen** [hotwired/turbo-rails#262]
This is not so much of an issue as sharing something that surprisingly worked for me. I am still a bit baffled about why and how this worked and would be interested to know if it seems like expected behavior and would be considered a good pattern or just a lucky artifact that should not be leaned on. 

My goal was to be able to update just the fields of a form while leaving the buttons in the state in which they were when submitted. Here is some simplified pseudo code to illustrate what worked: 

```html.erb
<!-- _form.html.erb -->
<%= form_with model: Post.new do |f| %>
   <div id="post-fields">
      <%= turbo_stream.update("post-fields") do %>
         <%= f.input :title %>
         <%= f.input :body %>
      <% end %>
    </div>
    <%= f.submit %>
<% end %>

<!-- new.html.erb -->
<%= render 'form' %>

<!-- create.turbo_stream.erb -->
<%= turbo_stream.update("post-fields") do %>
  <%= render 'form' %>
<% end %>
```

Nesting the turbo streams updating the same div within the form seemed to preserve the elements outside of the div.

**Comment by WriterZephos** [comment]
As far as I understand it this s how turbo is supposed to work, and I am relying on this behavior.

For example, I have a form in one of my apps that autosaves as you type. Behind the scenes I am simply submitting the form and rendering back a tiny partial the gets updates within my form to tell me if it has saves all my changes or not.

It's a super cool technique I was happy to discover, since it means I don't have to write an ajax call. The way the controller know what to do is by setting the value of a hidden field in the form when it autosubmits. This allows me to handle autosaving and manual form submission using the same controller action. The autosave saves a draft of my blog posts while the manual submission publishes them.

Hope this helps. I hope they don't change this!
