### ISSUE TITLE
Stop lazy loading requests when navigating to a new link with turbo drive

### ISSUE THREAD

**Issue by mferrerisaza** [hotwired/turbo-rails#339]
Hey all!

I'm lazy loading a very heavy request with a `turbo_frame` but since others part of the page are loaded while it loads some users are clicking links that take them to other pages navigating with `turbo_drive`. The problem is that the other page that is not heavy, is taking a lot to load because the server is first resolving the turbo_frame request and has to wait until that finishes to process the next one.

I was wondering if this is a bug or the expected behavior or if there is a way to stop previous requests from happening when the user navigates to a different page.

I'm using heroku for this and I know it doesn’t have HTTP2 yet so could this be related?

Thanks

**Comment by dhh** [comment]
Would make sense to me if we canceled any frame requests when drive navigates away. I actually thought we were doing this? Heroku not supporting H2 shouldn't be related to this. Either way, please explore this on hotwired/turbo, since that's where the Turbo framework itself lives. This is just for the integration with Rails.
