### ISSUE TITLE
Any idea when a refresh from turbo will next be done ?

### ISSUE THREAD

**Issue by defsdoor** [hotwired/turbo-rails#350]
Am specifically waiting for this commit - https://github.com/hotwired/turbo/pull/525

**Comment by marcelolx** [comment]
@defsdoor I don't think it is, the latest version of turbo is `7.1.0` and turbo-rails is pointing to that version https://github.com/hotwired/turbo-rails/blob/v1.1.1/package.json#L16, once a new release of Turbo is made then I think there will be made a new one of turbo-rails....

If the intention is to use the latest changes of Turbo you will have to point your package.json to the latest build available [here](https://github.com/hotwired/dev-builds/tags)

**Comment by dhh** [comment]
Indeed. Getting ready for Turbo 7.2.0 though. Shouldn't be long.

**Comment by defsdoor** [comment]
> If the intention is to use the latest changes of Turbo you will have to point your package.json to the latest build available [here](https://github.com/hotwired/dev-builds/tags)

What is this package.json you speak of ?  No webpackers here ;)

**Comment by marcelolx** [comment]
@defsdoor I'm not that familiar with the other approaches (still using webpacker), but you still probably should be able to download the release you want from the link I mentioned above and use the bundled version of Turbo (esm/umd) which is basically what this [gem does](https://github.com/hotwired/turbo-rails/tree/main/app/assets/javascripts) today... ofc, since 7.2.0 is on the way it may be better just wait
