### ISSUE TITLE
Morph Refresh Breaks Web Component Styles

### ISSUE THREAD

**Issue by modagavr** [hotwired/turbo-rails#552]
Using `morph` refresh method (turbo 8 beta + turbo-rails 2 beta)

Using [shoelace](https://shoelace.style) web components library

`turbo_stream_from @conversation`
with `broadcasts_refreshes` in Conversation model

buttons and other web component elements become ugly 
<img width="1350" alt="image" src="https://github.com/hotwired/turbo-rails/assets/49167406/f6b98305-48ba-4625-a8ff-ed7530130cc7">

how it should look like and **how it properly works with current latest stable packages** (turbo 7 + turbo-rails 1.5)
<img width="1350" alt="image" src="https://github.com/hotwired/turbo-rails/assets/49167406/ccbde72a-5472-4e6f-86be-c3f99348984a">

**Comment by modagavr** [comment]
Maybe idiomorph doesn't work well with Shadow DOM or something like that

**Comment by kotogavr** [comment]
+1
I have the same problem with the same setup.

**Comment by KonnorRogers** [comment]
Hi there! Shoelace maintainer here 👋. The problem exists because morphing libraries never re-run the constructor function of the web component so it ends up not having the expected default properties.

there's a pretty lengthy discussion here:

https://github.com/stimulusreflex/stimulus_reflex/issues/511#issuecomment-1066291116

the TLDR is that you need to provide all default attributes for the component up front in your server rendered HTML for it to work out of the box as expected.

**Comment by brendon** [comment]
@KonnorRogers, sounds like a difficult problem to solve elegantly. Is a solution being considered as part of the WebAwesome development?

**Comment by brendon** [comment]
In my case it was enough to add `data-turbo-permanent` to the element wrapping the shoelace form controls I was using. They don't need to re-render in my case as they're only displayed as examples in our form builder.

**Comment by KonnorRogers** [comment]
> @KonnorRogers, sounds like a difficult problem to solve elegantly. Is a solution being considered as part of the WebAwesome development?

Funny you say that, I actually made a prototype a couple of days ago that should solve majority of cases.

I'm not quite sure what issues I may hit, but I _think_ we could store initial values from the constructor and in the `attributeChangedCallback` if an attribute we expect to always be present becomes `null`, then we can revert it.

obvious caveats of storing more than you need is possible memory leaks and large amounts of GC, but that's a future problem.

if you have any reproductions of breaking examples, I'd be happy to take a look and see if I can cover the case.

doesn't help other components, but if it works like I think it will, I can at least write a mini blog post of how to have reflected default attributes play nicely with morphing.

**Comment by brendon** [comment]
In my case the form elements were losing their styling. I since discovered I was going to have a pretty hard time with stimulus controllers also so I've switched back to full page replacements for now.

I get the feeling that if I want to use morphing in the future I'm going to have to become deeply acquainted with the internals and I just don't have the headspace for that right now :)
