### ISSUE TITLE
idiomorph merges attributes on `<turbo-cable-stream-source>` and `connectedCallback()` doesn't run

### ISSUE THREAD

**Issue by mtomov** [hotwired/turbo-rails#638]
Hello 👋 

With Turbo page refreshes, and using the morph strategy, I've encountered an issue when the dom has a `<turbo-cable-stream-source>` element that has its `signed-stream-name` updated with a new reference as the underlying active record instance becomes different .. like `Post.find(1)` and then becomes `Post.find(2)`.

```html
<turbo-cable-stream-source channel="Turbo::StreamsChannel" signed-stream-name="IloybGtPaTh2WW1WaGJXRnBMMU4xYlcxaGNua3ZOamMwTUEi--52c09e728bd657fce386997af8697e3a05baf00ed91af32c813fc3acb4e71809" connected=""></turbo-cable-stream-source>
```

Trouble is that as idiomorph merges the attributes, and doesn't replace the entire element, the `connectedCallback()` from here doesn't run:

https://github.com/hotwired/turbo/blob/main/src/elements/stream_source_element.js#L6-L10

which in turn means that the streams stop working. 

One potential solution is to update the `stream_source_element.js` to watch for changes on its `signed-stream-name` attribute and kick off the `connectedCallback()` logic?

For now, I've borrowed a sample code by idea from another issue by @seanpdoyle and am doing this, which fixes the issue:

```js

addEventListener(
  "turbo:morph-element",
  ({ target, detail: { newElement } }) => {
    if (
      target.nodeName === "TURBO-CABLE-STREAM-SOURCE" &&
      newElement.nodeName === "TURBO-CABLE-STREAM-SOURCE"
    ) {
      target.outerHTML = newElement.outerHTML
    }
  }
)
```

**Comment by seanpdoyle** [comment]
Thank you for opening this issue. You're correct: integrating with morphing alters the mental model. 

Custom Elements' `connectedCallback()` and `disconnectedCallback()` (along with Stimulus' `connect()` and `disconnect()`) improved upon invoking code immediately, or listening for `DOMContentLoaded` events. 

There are similar improvements to be made to integrate with morphing. First, both the `<turbo-cable-stream-source>` and `<stream-source>` elements will need to [observe attribute changes](https://developer.mozilla.org/en-US/docs/Web/API/Web_Components/Using_custom_elements#responding_to_attribute_changes) by declaring their own `static observedAttributes` properties along with `attributeChangedCallback(name, oldValue, newValue)` callbacks. Those callbacks should execute the same initialization code as their current `connectedCallback()` methods.

That'll help resolve this issue. In addition to those changes, it'll be important to emphasize this pattern for consumer applications moving forward. JavaScript code (whether Stimulus controller or otherwise) should be implemented in a way that' resilient to both asynchronous connection and disconnection *as well as* asynchronous modification of attributes.

**Comment by seanpdoyle** [comment]
I've opened https://github.com/hotwired/turbo-rails/pull/650 to try and resolve this issue for `turbo-rails`. A similar PR will be required to `@hotwired/turbo` for `<stream-source>` element support.

**Comment by Michoels** [comment]
I have this issue as well, and @mtomov's patch fixed it for me for now.
